<?php
/**
 * Interactiv4 Base theme skeleton
 *
 * @category    design
 * @package     interactiv4_base
 * @copyright   Copyright (c) 2015 Interactiv4, S.L. (http://interactiv4.com)
 *
 * @var $this Mage_Page_Block_Html
 */
?>
<!DOCTYPE html>
<html lang="<?php echo $this->getLang(); ?>">
    <head>
        <?php echo $this->getChildHtml('head'); ?>
    </head>
    <body class="<?php echo $this->getBodyClass(); ?>">
        <?php echo $this->getChildHtml('skeleton'); ?>
        <?php echo $this->getAbsoluteFooter(); ?>
    </body>
</html>
